{{- if .Values.azureDocIntelligenceKey }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-document-intelligence-key-secret
type: Opaque
data:
  secret: {{ .Values.azureDocIntelligenceKey | b64enc }}
{{- end }}