apiVersion: v1
kind: Service
metadata:
  labels:
    app: textual-worker
  name: textual-worker
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: textual-worker
  template:
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
  ports:
    - port: 8843
status:
  loadBalancer: {}
