apiVersion: v1
kind: Service
metadata:
  labels:
    app: solar-worker
  name: solar-worker
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: solar-worker
  ports:
    - port: 8843
status:
  loadBalancer: {}
