{{- if (.Values.tonicai).use_ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "textual-api-server"
  namespace: {{ .Release.Namespace }}
  labels:
    dev.tonic.ai/managed-dns: external-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{.Values.prappDetails.name}}.dev.tonic.ai"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "3600"
spec:
  ingressClassName: "nginx"
  rules:
    - host: "{{.Values.prappDetails.name}}.dev.tonic.ai"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: "textual-api-server"
                port:
                  name: "https"
{{- end }}
