apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-worker
  name: solar-worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ (.Values.solar_worker).numberOfWorkers | default 1 }}
  selector:
    matchLabels:
      app: solar-worker
  strategy:
    type: {{ .Values.deployStrategy | quote | default "Recreate" }}
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: solar-worker
    spec:
      containers:
        - securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: var-logs-public
            mountPath: /usr/bin/solar/logs_public
          - name: var-logs
            mountPath: /usr/bin/solar/logs
          - name: vector-configuration
            mountPath: /usr/bin/solar/vector_config
          - name: tmp
            mountPath: /tmp
          env:
            - name: SOLAR_SECRET
              valueFrom:
                secretKeyRef:
                  name: solar-encryption-secret
                  key: secret
            - name: SOLAR_DB_DATABASE
              value: {{ .Values.solarDatabase.dbName }}
            - name: SOLAR_DB_USERNAME
              value: {{ .Values.solarDatabase.user }}
            - name: SOLAR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: solar-db-password
                  key: password
            - name: SOLAR_DB_PORT
              value: {{quote .Values.solarDatabase.port }}
            - name: SOLAR_DB_SSLMODE
              value: {{ .Values.solarDatabase.sslMode }}
            - name: SOLAR_DB_HOST
              value: {{ .Values.solarDatabase.host }}
            - name: ENVIRONMENT_NAME
              value: {{ .Values.environmentName }}
            - name: SOLAR_PYML_URL
              value: https://solar-ml:7701
            - name: SOLAR_WEB_URL
              value: https://solar-api-server
            - name: SOLAR_HTTPS_ONLY
              value: "true"
            - name: SOLAR_PY_URL
              value: https://solar-ml:7701
            - name: SOLAR_WORKER_HEALTH_PORT_HTTPS
              value: "8443"
            {{- if .Values.enableLogCollection }}
            - name: ENABLE_LOG_COLLECTION
              value: {{ .Values.enableLogCollection }}
            {{- end }}
            {{- if .Values.openAiKey }}
            - name: SOLAR_OPENAI_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-key-secret
                  key: secret
            {{- end }}
            {{- if (.Values.solar_worker).env}}
            {{- range $key, $value := .Values.solar_worker.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          {{- if (.Values.solar_worker).image }}
          image: {{ .Values.solar_worker.image }}:{{ .Values.solarVersion }}
          {{ else }}
          image: quay.io/tonicai/solar-worker:{{ .Values.solarVersion }}
          {{- end }}
          imagePullPolicy: IfNotPresent
          name: solar-worker
          ports:
            - containerPort: 8443
          resources:
            limits:
              memory: "12Gi"
            requests:
              memory: "6Gi"
              ephemeral-storage: "1Gi"
          startupProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: 8443
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 5
        - name: vector
          image: timberio/vector:latest-alpine
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: LOG_COLLECTION_FOLDER
              value: "/usr/bin/solar/logs_public"
          volumeMounts:
            - name: var-logs-public
              mountPath: "/usr/bin/solar/logs_public"
            - name: vector-configuration
              mountPath: "/usr/bin/solar/vector_config"
            - name: vector-working
              mountPath: "/etc/solar/vector_data"
          args:
            - "-w"
            - "--config"
            - "/usr/bin/solar/vector_config/vector.toml"
      restartPolicy: Always
      serviceAccountName: {{ template "solar.serviceAccountName" . }}
      imagePullSecrets:
      - name: solar-image-pull-secret
      volumes:
        - name: var-logs-public
          emptyDir: {}
        - name: var-logs
          emptyDir: {}
        - name: vector-configuration
          emptyDir: {}
        - name: vector-working
          emptyDir: { }
        - name: tmp
          emptyDir: {}
status: {}
