{{- $ports := (.Values.textual_api_server).ports | default dict }}
{{- $httpsOnly := $ports.httpsOnly | default true }}
{{- $httpPort := $ports.http | default 6880 }}
{{- $httpsPort := $ports.https | default 6443 }}
apiVersion: v1
kind: Service
metadata:
  name: textual-api-server
  namespace: {{ .Release.Namespace }}
{{- if  (.Values.textual_api_server).annotations }}
  annotations:
  {{- toYaml .Values.textual_api_server.annotations | nindent 4 }}
{{- else }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
{{- end }}
  labels:
    app: textual-api-server
spec:
  ports:
{{- if not $httpsOnly }}
    - name: "http"
      port: 80
      targetPort: {{ $httpPort }}
{{- end }}
    - name: "https"
      port: 443
      targetPort: {{ $httpsPort }}
  type: {{ (.Values.textual_api_server).service_type | default "LoadBalancer" }}
  selector:
    app: textual-api-server