apiVersion: v1
kind: Service
metadata:
  name: solar-ml
  namespace: {{ .Release.Namespace }}
  labels:
    app: solar-ml
spec:
  selector:
    app: solar-ml
  ports:
    - port: 7701
status:
  loadBalancer: {}